### ISSUE TITLE
Import data back

### ISSUE THREAD

**Issue by alex-moreno** [gbraad/gauth#113]
Same question as Import Option, without requesting a new feature, how do you import the data that you have exported previously? I can't find in the documentation how to do it.

Thanks.

**Comment by greggles** [comment]
This option doesn't exist as a complete feature. However, you can do it manually.  The `gauth-export.json` contents look something like this:

```
[{"name":"alice@google.com","secret":"JBSWY3QWERDK3PXP"}]
```

To "import" that value:

1. Open the browser where you want to import it
2. Click the pencil icon in the top right
3. Click the "Add" button at the bottom left of the screen
4. For account name, copy/paste in the "name" value from the json (or you can edit it if you want).
5. For the secret key, copy and paste in the "secret" value from the json (this is the one that you must get right).


That's it. If you have a lot of keys I guess it could be tedious, but otherwise it should be done quickly.

**Comment by alex-moreno** [comment]
ah great, thanks, I'll try that

**Comment by davchana** [comment]
Thanks @gbraad , I came here from https://github.com/gbraad/gauth/issues/112#issuecomment-444687832

Those apply for desktop browsers; but my use case was for android chrome browser.
