### ISSUE TITLE
Logged in and keys have vanished

### ISSUE THREAD

**Issue by murraci** [gbraad/gauth#90]
Using the desktop client on OS X 10.11.4

Every key except Alice@google has vanished.

Had a backup up of whole Gauth application support folder and restored it but that hasn't worked. I still cannot see the keys in the app. Where exactly are the keys stored in the application support folder?

**Comment by gbraad** [comment]
Hi, this is very unfortunate. Would you next time also be able to link to the reported issue? The information you provide is at the moment too little to provide support.

Although I can guess what is wrong; you have made a backup of the extension folder and not of the browser folder. The information of this extension is stored in the browsers' localstorage database. Due to some unfortunate events, the browser can decide to clear its cache and cookie storage and you would loose your data.

Please describe the steps that led to the lose of data and perhaps even report this to the browser vendor.

For this reason, the application has an export function in 'Settings'. Always keep a physical copy of your secrets in a safe place. I am sorry, but I can not help you any further.

**Comment by murraci** [comment]
Hi 

Thanks for your response. For some unknown reason they keys have now simply returned to the client. Very strange but I have now backed them up by the method you have suggested. 

Thanks for your help.

**Comment by gbraad** [comment]
You have been very lucky. BTW, which browser did you use?

**Comment by murraci** [comment]
I used a desktop client: GAuth. Not sure if that's what you mean by browser? I don't use a plugin for Firefox or Chrome. Can't find a version on the client.

**Comment by murraci** [comment]
I've noticed something different. It says GAuth at the top again like normal now, whereas yesterday when the keys weren't visible, it said https://gauth.apps.gbraad.nl/.

**Comment by gbraad** [comment]
Hmmmm.... where did you download the desktop application from? This was an offering that I stopped doing quite a while ago. It should now be browser-only.

**Comment by murraci** [comment]
You know, I've no idea! Yesterday when I was having problems I couldn't find where I downloaded it from. It was most likely Softpedia as I see it's still available there. I wanted to use a standalone client as I felt it was added security against a browser exploit. Do you think this is bad practice?

**Comment by gbraad** [comment]
In a way you are right, although the usecase was never to host it on a desktop in the first place. This places both the password and the second factor in arm's reach (mobile use was). Softpedia might have an older version stored which I based on nw, but this has been a long time ago.

I might reconsider. Just at the moment I want to convert first to a webextension. This in itself is not difficult, but needs me to reserve time.

At least I am happy it got resolved. Note: For future, always keep a hard copy in a safe place...

**Comment by murraci** [comment]
Yes I understand and you're also right. To counter that physical threat I use multiple layers of encryption on my laptop. I'm relatively happy with my set up. 

I've put an encrypted copy of the JSON key file in the cloud and will now get myself a hard copy :)

Thanks again for your assistance and best of luck with everything!
