### ISSUE TITLE
Zero coming as OTP even if the valid secret key

### ISSUE THREAD

**Issue by durgaprasade** [gbraad/gauth#99]
Hi,
I have a secret key (MNWHA53EN52GS3TRI5AWC6RRGIZSCQCAFEUCU23MKFBVISC7GM2Q) which is generating by my application, When i am using the key in GAuth Authenticator its giving "0" as a OTP. ( System time is sync with google time)

In Other chrome extensions like ( Authenticator) or Scan QR image in google authenticator( mobile app) are giving valid OTP.

Are there any boundary conditions generate the valid secret key? why its not generating the valid OTP? or am i miss something?

**Comment by amit** [comment]
I could not reproduce this issue with latest commit. I am getting codes for this secret key.

**Comment by preactive** [comment]
I tested on the web site http://gauth.apps.gbraad.nl with durgaprasade's code and I got 0 as well:

Is the site at the same commit level as this repo?

Google Chrome	56.0.2924.87 (Official Build) (64-bit)
Revision	0e9a9a6f3676ae439b78cd9b3f62b4193c3ac7d5-refs/branch-heads/2924@{#895}
OS	Linux Fedora 24
JavaScript	V8 5.6.326.50
Flash	25.0.0.127 /home/username/.config/google-chrome/PepperFlash/25.0.0.127/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Command Line	/usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end
Executable Path	/opt/google/chrome/google-chrome

**Comment by amit** [comment]
I tested it on self hosted site with latest master.



On Apr 4, 2017 10:03 AM, "Michael Messmer" <notifications@github.com> wrote:

I tested on the web site http://gauth.apps.gbraad.nl with durgaprasade's
code and I got 0 as well:

Is the site at the same commit level as this repo?

Google Chrome 56.0.2924.87 (Official Build) (64-bit)
Revision 0e9a9a6f3676ae439b78cd9b3f62b4193c3ac7d5-refs/branch-heads/2924@
{#895}
OS Linux Fedora 24
JavaScript V8 5.6.326.50
Flash 25.0.0.127 /home/username/.config/google-chrome/PepperFlash/
25.0.0.127/libpepflashplayer.so
User Agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/56.0.2924.87 Safari/537.36
Command Line /usr/bin/google-chrome-stable --flag-switches-begin
--flag-switches-end
Executable Path /opt/google/chrome/google-chrome

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/gbraad/gauth/issues/99#issuecomment-291565800>, or mute
the thread

**Comment by preactive** [comment]
@durgaprasade what application is generating this code?

**Comment by bkowald** [comment]
I get an OTP of 0 for the manual entry key of KN2XAZLSKNSWG4TFORFWK6KHN5SXGSDFOJSQ. I am generating manual entry keys with this library
https://github.com/brandonpotter/GoogleAuthenticator

**Comment by gbraad** [comment]
@netluxe I have (re)pushed the latest version to the hosting service. Seems there was likely an issue with the publishing script... :-s sorry, my bad
